### ISSUE TITLE
Error while building database

### ISSUE THREAD

**Issue by dcdanko** [knights-lab/BURST#11]
I am getting an error while trying to build a database with burst.

I am following the directions [here](https://github.com/knights-lab/BURST/blob/master/embalmlets/bin/Readme_utils.txt)  to download and process all reference genomes.

I built burst from source using the command `gcc burst.c -march=native -fwhole-program -fopenmp -Ofast`

Any help would be appreciated.

```
# burst -r AllGenomes.fasta -a AllGenomes.acx -o AllGenomes.edx -d DNA -s
This is BURST [v0.99.7f]
 --> Using accelerator file AllGenomes.acx
 --> Creating DNA database (assuming max query length 500)
 --> Shearing references longer than 500
Using up to AVX-128 with 20 threads.

Parsed 13406 references.

Initiating database shearing procedure [shear 515, ov 515].
Using compressive optimization (1 partitions; ~13406 refs).
[0] First pass: populated bin counters [184.051535]
--> Out of the 23364680418 original places, 23315672793 are eligible.
OOM:Ptrs_X
```

The output from time suggests that this is not an out of RAM issue (the machine being used has 96GB RAM).
```
Command exited with non-zero status 3
        Command being timed: "burst -r AllGenomes.fasta -a AllGenomes.acx -o AllGenomes.edx -d DNA -s"
        User time (seconds): 3613.36
        System time (seconds): 21.14
        Percent of CPU this job got: 1502%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 4:01.94
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 23344972
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 5839172
        Voluntary context switches: 58
        Involuntary context switches: 24412
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 3
```

**Comment by GabeAl** [comment]
This means it has run out of memory. BURST requires about 10 times as much
RAM as the size of the initial fasta file on disk. If you have insufficient
RAM, you can try adding a flag like -dp 4 to partition database building
into phases, and/or split the original fasta into multiple databases and
run them separately, performing downstream processing to deduplicate and
merge the resulting tables.

Hope this helps!
Gabe

**Comment by dcdanko** [comment]
Thanks for the advice.

Just a note though `-dp 4` did decrease the average RAM usage but not the peak. Building the accelerator still takes a ton of RAM (357G for a 29G fasta in my case) so I had to move to a higher RAM machine.

No issues on the bigger machine though.
