### ISSUE TITLE
alltax.txt format

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#13]
Hi,

I am not using the RefSeq download as described in the readme, so I need to know the format for the alltax.txt file to make it myself from my own fasta files.

Thanks.

**Comment by GabeAl** [comment]
Hi Theo,

It's a tab-delimited file containing the following. 

Column 1: The complete sequence header of each reference (minus the ">")
Column 2: The corresponding semicolon-delimited taxonomy string (preferably in GreenGenes- or SILVA-style ranked format)

Other columns are not used.

Hope this helps!
