### ISSUE TITLE
db size

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#15]
Hi,

I have a 200 Gb sequence resource to build into a db. How much memory will this take? I have tried 900 Gb with -db 10 option but still run out of RAM.

Thanks.

**Comment by GabeAl** [comment]
"-db 10" is not a valid flag -- I think you mean -d DNA? You also need the
-s flag when building with whole genomes. I'd set '-s' somewhere in the
range of 1000 to 2000 for a database of this size. Have you tried -db
QUICK? If you want to stick with -d DNA, I'd suggest also using -dp 10
(maybe this is what you meant at the beginning as well!).

Cheerio,
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Typo.. I meant -dp 10. I am also using -s 1500. Trying with -dp 30 at the moment. Is there any guide as to how big the db might be based on the genomes? Is the 'QUICK' optino smaller or quicker to build or quicker to search? Not clear on the difference between QUICK and DNA. Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
I have now tried up to -dp 36 and with 990 GB RAM, it is still killed, with the last log lines:

Scanning accelerator [9117952 / 9131157]
Scanning accelerator [91

I will try 'QUICK'
