### ISSUE TITLE
line count error

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#16]
Hi,

I get this error with my db:

EDB database provided. Parsing...
 --> EDB: Fingerprints are DISABLED
 --> EDB: Parsing compressed headers
 --> EDB: Sheared database (shear size = 158)
 --> EDB: Unique-reference database
 --> EDB: 72350 refs [72480 orig], 4522 clumps, 1658 maxR
ERROR: line count != '>' * 2

Any ideas? 

Thanks.

**Comment by GabeAl** [comment]
What do your queries look like? They have to be linearized fasta (no line
breaks in the sequence) and not contain any > character except the first
character of every header. The file must also end on a newline. Hence, if
you have N queries, there must be exactly N ">" characters and exactly 2N
newline characters.

Does this help?

Cheerio,
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Ok, thanks. I missed that in the manual. I will have to rebuild my DBs :( 
Interstingly, the build run did not pick up the format problem.

Theo

**Comment by GabeAl** [comment]
It may be that only your queries need to be formatted in this way. Although
it wouldn't hurt to ensure both are formatted this way for accuracy.

**Comment by theo-allnutt-bioinformatics** [comment]
Yes, both needed to be formatted to single line sequence. Thanks.
