### ISSUE TITLE
Strange encoding characters in output file

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#20]
Hi,
my blast style output is including some very unusual text codes, e.g.



	

i.e.

(ENQ)(ENQ)(ENQ)(LF)
(LF)
(ENQ)(BS)(ENQ)(SOH)

This prevents any downstream processing of the files and they are difficult to remove automatically.
Is ths a bug that can be fixed easily?

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
I added this to my pipeline for burst.. removed all special text codes and lines starting with tabs or newlines.

sed -i 's/[^[:print:]\t]//g' out.burst
sed -i '/^$/d' out.burst
sed -i '/^\t/ d' out.burst

**Comment by GabeAl** [comment]
Hi Theo,

BURST does not add these codes. It could either be a bug or some issue with
the formatting of your queries and references.

If you suspect it is a bug, could you provide a minimal reproducible
example so I can debug the problem? Including the reference sequence file
and commands to make DB, and query file and commands to align, as well as
the output file you're getting and what version of burst was used.


Thanks!
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks, on further checking I think this is a problem with how I am saving reads with no alignment.. more difficult than I had thought.

**Comment by theo-allnutt-bioinformatics** [comment]
I've had to reopen this issue. The problem definitely is with the BURST output file but it is very difficult to replicate. Random output files contain the bad text codes. I may have to upload the full db and input files causing the problem. I will update when I can nail it down.

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
I've had to reopen this issue. The problem definitely is with the BURST output file but it is very difficult to replicate. Random output files contain the bad text codes. I may have to upload the full db and input files causing the problem. I will update when I can nail it down.

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
This is not resolved, but it is not possible to replicate.
