### ISSUE TITLE
Burst finding no hits

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [knights-lab/BURST#24]
Hi, 

I have built a db:

burst_linux_DB15 -r bact.fa -o bact.edx -a bact.acx -d DNA 151 -i 0.90 -t 48 -s 1500 -n -dp 2

and run burst agains my fasta files (all single line files):

burst_linux_DB15 -r bact.edx -a bact.acx -q 37.fasta -o 37bact.burst -fr -w -m FORAGE -i 0.92 -t 12 -n --skipambig

But burst finds no hits at all..  What could cause this? It was working fine with an earlier db I made with 0.95 ID.

Thanks,

Theo

output:

This is BURST [v0.99.8 special edition [PT2.5]]
Hotloading is disabled
 --> Using accelerator file /stornext/HPCScratch/home/allnutt.t/db/burst/bact.acx
 --> Also considering the reverse complement of reads
 --> Allowing whitespace in query name output
 --> Setting run mode to FORAGE
 --> Setting identity threshold to 0.920000
 --> Setting threads to 12
 --> Setting N penalty (ref N vs query A/C/G/T)
 --> Skipping highly ambiguous sequences
Using up to AVX-128 with 12 threads.
 --> [Accel] Accelerator found. Parsing...
 --> [Accel] Total accelerants: 14722311765 [bytes = 37070480817]
 --> [Accel] Reading 0 ambiguous entries

EDB database provided. Parsing...
 --> EDB: Fingerprints are DISABLED
 --> EDB: Parsing compressed headers
 --> EDB: Sheared database (shear size = 167)
 --> EDB: Unique-reference database
 --> EDB: 9442912 refs [9489828 orig], 590182 clumps, 1667 maxR
Parsed 12850551 queries (51.648549). Calculating minMax...
Found min 100, max 151 (0.001335).
Converting queries... Converted (0.108706)
Copying queries... Copied (0.014017)
Sorting queries... Sorted (0.796053)
Copying indices... Copied (0.010782)
Determining uniqueness... Done (0.144244). Number unique: 10845913
Collecting unique sequences... Done (0.061833)
Creating data structures... Done (0.071604) [maxED: 13]
Processing reverse complements... Processed (0.839319) [offset 1591144483 / 1591144483]
Determining query ambiguity... Determined (0.018165)
Creating bins... Created (0.425870); Unambig: 0, ambig: 0, super-ambig: 21691826 [0,0,21691826]
Re-sorting... Re-sorted (1.500146)
Calculating divergence... Calculated (0.264698) [36.707885 avg div; 150 max]
Fingerprints not enabled
Setting QBUNCH to 16
Using ACCELERATOR to align 0 unique queries...
Search Progress: [0.00%]
Search complete. Consolidating results...

**Comment by GabeAl** [comment]
Hi Theo,

Here all queries are registering as super-ambiguous because they are told
they may contain more errors than the unambiguous alignment engine can
support. In default high throughout mode burst is optimized for high
identity searches (above 93.5% identity for burst12 or above 95% for
burst15).

So what can you do? Either omit the -sa flag (slow!) or add the -hr flag
(fast, but may miss a few low-identity alignments by chance!). Another
option is to use >93.5% identity with burst12 and otherwise change nothing.
:-)

Cheerio,
Gabe

**Comment by theo-allnutt-bioinformatics** [comment]
Ok, will burst12 work with the burst15 db?

I'm not sure in this case what 'ambiguous' means. I thought it meant 'contains Ns', of which there are very few in my reads because they were already filtered. Do you mean that a read is ambiguous if it hits more than one target? Because I certainly want to retain all hits, that is why I am using forage (I am applying my own LCA downstream so I want all hits).

Thanks,

Theo

**Comment by theo-allnutt-bioinformatics** [comment]
I tried burst12 with 93.5% and -hr and again got no hits, burst just stopped at the point shown below:

This is BURST [v0.99.8 special edition [PT2.5]]
Hotloading is disabled
 --> Using accelerator file /stornext/HPCScratch/home/allnutt.t/db/burst/bact.acx
 --> Also considering the reverse complement of reads
 --> Allowing whitespace in query name output
 --> Setting run mode to FORAGE
 --> Setting identity threshold to 0.935000
 --> Setting threads to 48
 --> Setting N penalty (ref N vs query A/C/G/T)
 --> Skipping highly ambiguous sequences
 --> WARNING: Heuristic mode set; optimality not guaranteed at low ids
Using up to AVX-128 with 48 threads.
 --> [Accel] Accelerator found. Parsing...
 --> [Accel] Total accelerants: 285561882 [bytes = 718069548]
 --> [Accel] Reading 0 ambiguous entries

EDB database provided. Parsing...
 --> EDB: Fingerprints are DISABLED
 --> EDB: Parsing compressed headers
 --> EDB: Sheared database (shear size = 167)
 --> EDB: Unique-reference database
 --> EDB: 9442912 refs [9489828 orig], 590182 clumps, 1667 maxR
Parsed 12850551 queries (66.047007). Calculating minMax...
Found min 100, max 151 (0.001377).
Converting queries... Converted (0.109861)
Copying queries... Copied (0.012468)
Sorting queries... Sorted (0.863195)
Copying indices... Copied (0.011030)
Determining uniqueness... Done (0.120968). Number unique: 10845913
Collecting unique sequences... Done (0.061042)
Creating data structures... Done (0.066418) [maxED: 10]
Processing reverse complements... Processed (0.918230) [offset 1591144483 / 1591144483]
Determining query ambiguity... Determined (0.416447)
Creating bins... Created (0.516830); Unambig: 21672968, ambig: 18858, super-ambig: 0 [18858,21691826,21691826]
Re-sorting... Re-sorted (1.470186)
Calculating divergence... Calculated (0.246028) [36.682416 avg div; 150 max]
Fingerprints not enabled
Setting QBUNCH to 16
Using ACCELERATOR to align 21691826 unique queries...

**Comment by GabeAl** [comment]
Did you rebuild the database with burst12?

**Comment by theo-allnutt-bioinformatics** [comment]
No, I will try that. Thanks.

There doesn't seem to be any information on the difference between Burst12 and 15 in the manual. Are there plans to fix that?

**Comment by GabeAl** [comment]
There are plans to do so now, thanks to this ticket and your valuable
input. Thanks again for your continued engagement regarding burst!

Cheerio,
Gabe
