### ISSUE TITLE
LCA assignment fails 

### ISSUE THREAD

**Issue by Leob44** [knights-lab/BURST#26]
I am trying to perform a LCA assignment to a databank fasta file. I have several hits, but the column taxonomy doesn't show up in the output table. What do I do wrong? 

`
./burst12 -b ../taxonomy.txt -q ./Trimmed_filtered_seqs/combined_seqs.fna -a ../GGTA1_bank.acx -r ../GGTA1_bank.edx -o LCA_results/output_LCA12.txt --taxacut 0.85`

**Comment by GabeAl** [comment]
It's probably a formatting issue with your taxonomy and/or reference
headers.

Ensure that you are using a linearized fasta (repeats of one line for the
header, and *one line for the entire sequence*), and that the taxonomy file
does NOT include the ">" character in the first column.

If you post your taxonomy file I can also take a look if this doesn't fix
it for you. :)

Hope this helps!

Cheerio,
Gabe

**Comment by Leob44** [comment]
It was because of the '>' character which indeed should not appear in the taxonomy file ! Now it works fine, thanks a lot !

**Comment by Leob44** [comment]
I have another issue : In my output file, I have several hits where no taxonomy is displayed. When I come back to the taxonomy file, I can find the corresponding line and the taxonomy is present, and respect the requirement. 

By advance thank you :)

**Comment by Leob44** [comment]
[index_all.txt](https://github.com/knights-lab/BURST/files/4623567/index_all.txt)

**Comment by Leob44** [comment]
[output_TEST16s.txt](https://github.com/knights-lab/BURST/files/4623570/output_TEST16s.txt)

**Comment by GabeAl** [comment]
Hello,

This is not a properly formatted taxonomy file. As stated in the readme, it
must be "a tab-delimited taxonomy file where the first column contains the
entire sequence header for each sequence in the original fasta file, and
the second column contains semi-colon-separated taxonomy"

The index file you provided has three columns, so BURST is using column 2
as the taxonomy as stated. Because your second column is not a delimited
taxonomy string but just a name, burst treats it as a taxonomy with just 1
level. Hence, every time there is disagreement among the potential species
a read can map to, the LCA output field is interpolated down to the root
(blank).

Hope this helps!
Gabe

**Comment by Leob44** [comment]
Han yeah, I appear to have been stupid on this one hehe ! But then In many cases, I get only indication for the family, and not the possible specie, despite 100% identity cases. How can this be explained ?  I would like to have specie/strain distributions in several diseases. I feel there something I get wrong, probably about the tree.. Should I change taxacut ? 

(sorry for the approximate english, French people are so bad at it :))

**Comment by GabeAl** [comment]
No worries. :)

The taxonomy reported is LCA taxonomy (lowest common ancestor). When a read
maps equally well to different species, only the genus in common is
returned. Sometimes a read may map across genera, in which case the family
in common is returned. And so on. There are some instances of a read
mapping across kingdoms! (A read may map to both a bacterium and an
archaeon), in which case the field will be completely blank.

To tune the stringency thresholds for when LCA is triggered for taxonomy
reporting, play with --taxacut.

Cheerio,
Gabe

**Comment by GabeAl** [comment]
One more thing, if you would like the redistribution based on the assigned
genome (first column of the b6 output), which BURST tries to be smart about
selecting when there are ties (it's the "CAPITALIST" algorithm which
assigns as your genome ID the genome with the most support from all the
other reads in your dataset), you can do this easily in R. Simply load up
the taxa file, keeping the first column as the rownames, and index the
taxonomy data frame by the first column of the b6 file (or more easily, the
consolidated table of output from embalmulate).

The returned data frame will contain the full-rank taxonomy for all of the
genomes matched with BURST without LCA.

So after running BURST and embalmulate to get your genomes.txt table, in R:
map = read.delim("index_all.txt",head=F,row=1)
taxa = read.delim("genomes.txt",row=1)
taxa$taxonomy = map[rownames(taxa),1]

Now you'll have the full table with the genome, the counts per sample, and
the full taxonomy string (under the column "taxonomy"), just like QIIME1.
Hope this helps!

Cheerio,
Gabe

**Comment by Leob44** [comment]
It does help indeed ! Thank you so much for this exhaustive explanation !!
