### ISSUE TITLE
Make taxcut fractional

### ISSUE THREAD

**Issue by danknights** [knights-lab/BURST#3]
So if I want to use .85 confidence I can just say .85 instead of 6.6667

**Comment by bhillmann** [comment]
@GabeAl I recall talking about this the other day. Can taxacut take a float?

**Comment by GabeAl** [comment]
I think this has been added to SHOGUN now as a wrapper for taxacut. 

Agreed it's not the most straightforward, but floating point does imply a continuum, which is misleading as this number is quite (quite!) discrete. It goes from allowing 50% disagreement (1/2) to 33% (1/3) to 25% (1/4) and so on. A number like "60%" or "40%" would probably both map to taxacut 2 (50%) and produce exactly identical results, much to the confusion of users. 

The algo would need to be rewritten in floating point for this to work. Doable. But dubious benefit (?) now that it's wrapped anyway in SHOGUN, eh?

**Comment by GabeAl** [comment]
OK it's done. Same release page (and in SOP) along with other tweaks
