### ISSUE TITLE
Embalmulate gone?  No method for condensing b6 into OTU table?

### ISSUE THREAD

**Issue by transcript** [knights-lab/BURST#9]
Looking over other links and documentation, it appears that you merged the embalmulate tool, which condenses the b6 output into a QIIME OTU table, into this repo.

However, I don't see embalmulate as a script in the most recent release, and there doesn't appear to be any explanation on how to use this feature.  Does this still exist?

**Comment by GabeAl** [comment]
Thanks for pointing this out!

It appears the binaries never made it into the repo, although they should
have. Today, I will re-upload all the embalmlets including embalmulate
here!

Usage is very spartan and each embalmlet only does one thing. I will
compile a short readme about the capabilities of each and place it here as
well.
